name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'oracle'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.2.0'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install jextract
        run: |
          wget https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_linux-x64_bin.tar.gz
          tar -xvf openjdk-25-jextract+2-4_linux-x64_bin.tar.gz
          chmod +x jextract-25/bin/jextract
          chmod +x generate_source.sh
          bash generate_source.sh
          
      - name: Build with Gradle
        run: ./gradlew build test
