name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.2.0'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get install libavformat-dev

      - name: Install jextract
        run: |
          find /usr -name avformat.h
          pwd
          ls -al
          wget https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_linux-x64_bin.tar.gz
          tar -xvf openjdk-25-jextract+2-4_linux-x64_bin.tar.gz
          chmod +x jextract-25/bin/jextract
          jextract-25/bin/jextract /usr/include/x86_64-linux-gnu/libavformat/avformat.h -t com.asrevo.ffmpeg -l avformat --output src/main/java
          
      - name: Build with Gradle
        run: ./gradlew build test
